### ISSUE TITLE
looks wrong

### ISSUE THREAD

**Issue by malie** [fumieval/incremental#3]
https://github.com/fumieval/incremental/blob/4e7a06895190717875a8bb3713a78d5160589c23/src/Data/Incremental.hs#L91

Hi, I'm making many assumptions what your code might mean, but I'd imagine this line should read
```
  Upsert a d <> Update e = Upsert (patch a e) (d <> e)
```
since you probably don't intend to drop the 'update e' in case 'a' is inserted.
Did I guess right?

**Comment by fumieval** [comment]
Ah, good catch. Fixed in b01b02ca

**Comment by fumieval** [comment]
Closing as fixed
